### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by thethorne48**
Now the files are in one PR. Sorry about the spam!

### CODE REVIEW

**Comment by dhoer** [comment]
If you would update the VERSION in spec helper, that should get the build to pass.

**Comment by thethorne48** [comment]
The tests are complaining about a Boolean that isn’t being set. The stack
trace isn’t very helpful either.

**Comment by dhoer** [comment]
I have a fix for that.  Let me get back to you in a bit.

**Comment by dhoer** [comment]
You will need to add the following line to appveyor.yml: https://github.com/dhoer/chef-nssm/blob/master/appveyor.yml#L25-L26

**Comment by dhoer** [comment]
I think that should fix it

**Comment by dhoer** [comment]
Thanks for the PR and your interest in adopting the cookbook.  Once the build turns green, I will grant you collaborator access on this repo and on the Chef account in supermarket.  BTW, what is your account name on Chef supermarket?

**Comment by thethorne48** [comment]
Ok adding that line. 
This is what I get now 
`Failure/Error:
       ChefSpec::SoloRunner.new(
         file_cache_path: CACHE, platform: 'windows', version: '2008R2', step_into: 'windows_logrotate'
       ) do |node|
         node.override['windows_logrotate_test']['username'] = 'vagrant'
         node.override['windows_logrotate_test']['password'] = 'vagrant'
         ENV['SYSTEMDRIVE'] = 'C:'
       end.converge(described_recipe)

     Chef::Exceptions::ValidationFailed:
       windows_logrotate[logrotate test] (windows_logrotate_test::default line 6) had an error: Chef::Exceptions::ValidationFailed: Property sensitive must be one of: TrueClass, FalseClass!  You passed nil.
     # /var/folders/dj/nnc5vjmn4415tvdkrhpx57gnp6pnhq/T/d20171025-7361-1qfkgpb/cookbooks/windows_logrotate/providers/default.rb:44:in `block (2 levels) in class_from_file'
     # /var/folders/dj/nnc5vjmn4415tvdkrhpx57gnp6pnhq/T/d20171025-7361-1qfkgpb/cookbooks/windows_logrotate/providers/default.rb:43:in `block in class_from_file'
     # ./spec/unit/resources/default_spec.rb:11:in `block (2 levels) in <top (required)>'
     # ./spec/unit/resources/default_spec.rb:15:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # Chef::Exceptions::ValidationFailed:
     #   Property sensitive must be one of: TrueClass, FalseClass!  You passed nil.
     #   /var/folders/dj/nnc5vjmn4415tvdkrhpx57gnp6pnhq/T/d20171025-7361-1qfkgpb/cookbooks/windows_logrotate/providers/default.rb:44:in `block (2 levels) in class_from_file'`

**Comment by dhoer** [comment]
I didn't realize the tls2 entry was there already.  So the issue was the url cert expired.  I would go with a new download url.  You can get that by going to download page and download the app and see what the url is.  I don't know if the cert expired means the pilot url will deleted in the near future or not. I wish I knew a better url to use that would be permanent from sourceforce.

**Comment by thethorne48** [comment]
Yeah I looked into that. We could write in the logic to follow redirects from their 'latest' link but that would be a little annoying. I am just dropping the ssl portion and relying on the sha256 checksum

**Comment by dhoer** [comment]
Ok, I just don't know if that means they plan to delete the url as well.

**Comment by thethorne48** [comment]
No they leave the old versions there with the same link. I think the cert was just getting caught by my proxy and disabled

**Comment by dhoer** [comment]
I thought about trying to get the author to release from github, but I think he makes money from all of the spam on sourceforge.

**Comment by thethorne48** [comment]
I would think that's the case. We can extend the library to pull 'latest' at some point when time is plentiful

**Comment by dhoer** [comment]
I invited you to be a collaborator. What is your account on chef, so I can make you the primary?  You can either keep the fork or make new repo, just be sure to update the view source and view issues on Chef when you do that.

**Comment by thethorne48** [comment]
Thanks! Its admlt
Will do!

**Pull request merged**
